import moment from "npm:moment-timezone";
import type { Choices } from "./choices.types.ts";

export const initialChoices: Choices = {
  eventTypes: [
    "ingresses",
    "aspects",
    "retrogrades",
    "planetaryPhases",
    "annualSolarCycle",
    "monthlyLunarCycle",
    "dailySolarCycle",
    "dailyLunarCycle",
    "twilights",
  ],
  ingresses: [
    //
    "signs",
    "decans",
    "peaks",
  ],
  signIngressBodies: [
    "sun",
    "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  decanIngressBodies: [
    "sun",
    "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  peakIngressBodies: [
    "sun",
    "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  aspects: [
    //
    "majorAspects",
    "minorAspects",
    "specialtyAspects",
  ],
  majorAspectBodies: [
    "sun",
    // "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  minorAspectBodies: [
    "sun",
    // "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  specialtyAspectBodies: [
    "sun",
    // "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  retrogradeBodies: [
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    // "lunar apogee",
  ],
  planetaryPhaseBodies: ["venus", "mercury", "mars"],
  /** @description The Inlet */
  // latitude: 40.7128,
  // longitude: -74.006,
  /** @description Rittenhouse Square, southeast corner of the fountain */
  latitude: 39.949309,
  longitude: -75.17169,
  start: moment.tz("2025-06-07", "America/New_York").toDate(),
  end: moment.tz("2025-07-10", "America/New_York").toDate(),
};
