services:
  postgres:
    image: postgres:17
    container_name: lexico-ingestion-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lexico_ingestion
    volumes:
      - lexico-ingestion-postgres-data:/var/lib/postgresql/data

volumes:
  lexico-ingestion-postgres-data:
