import type { KnipConfig } from "knip";

const config: KnipConfig = {
  $schema: "https://unpkg.com/knip@5/schema.json",

  // Globally ignored file patterns (tests, build output, caches)
  ignore: [
    "**/*.test.ts",
    "**/*.spec.ts",
    "**/dist/**",
    "**/node_modules/**",
    "**/.nx/**",
    "**/coverage/**",
  ],

  // Binaries invoked via project.json targets or scripts, not imported in code
  ignoreBinaries: [
    "terraform", // Terraform CLI, used for infrastructure provisioning
  ],

  // devDependencies used via npx, CLI, or ESLint config (not directly imported)
  ignoreDependencies: [
    "@nx/eslint-plugin", // Loaded dynamically by Nx ESLint integration
    "@nx/js", // Nx JavaScript/TypeScript plugin (auto-detected by Nx)
    "@nx/web", // Nx web plugin (auto-detected by Nx)
    "@semantic-release/commit-analyzer", // semantic-release plugin, referenced in .releaserc.json
    "@semantic-release/release-notes-generator", // semantic-release plugin
    "@semantic-release/github", // semantic-release plugin
    "@semantic-release/npm", // semantic-release plugin
  ],

  // Allow exports that are only used in the same file (common for barrel re-exports)
  ignoreExportsUsedInFile: true,

  // JimmyPaolini is a GitHub profile page with no buildable code — skip analysis
  ignoreWorkspaces: ["applications/JimmyPaolini"],

  workspaces: {
    // Root workspace: scripts, base configs, and Nx configuration files
    ".": {
      entry: [
        "scripts/**/*.{js,ts,sh}",
        "vitest.config.base.ts",
        ".releaserc.json",
        ".ncurc.cjs",
        "validate-branch-name.config.cjs",
      ],
      ignore: [
        "**/*.test.ts",
        "**/*.spec.ts",
        "**/dist/**",
        "**/coverage/**",
        "applications/JimmyPaolini/**",
      ],
      project: "**/*.{js,ts,mjs,cjs}",
    },

    // caelundas: Node.js CLI for astronomical calendar generation
    "applications/caelundas": {
      ignore: [
        "src/**/*.test.ts",
        "src/**/*.integration.test.ts",
        "src/**/*.end-to-end.test.ts",
        "output/**", // Generated calendar output files
        "testing/**", // Test fixtures and setup
      ],
      project: "src/**/*.ts",
    },

    // lexico: TanStack Start SSR web application with Supabase backend
    "applications/lexico": {
      entry: [
        "src/client.tsx", // Client-side entry point
        "src/router.tsx", // TanStack Router configuration
        "src/routes/**/*.tsx", // File-based routing — all route files are entry points
      ],
      ignore: [
        "src/routeTree.gen.ts", // Auto-generated by TanStack Router
        "src/lib/database.types.ts", // Auto-generated by Supabase CLI
        "src/lib/auth.ts", // Supabase auth utilities (used at runtime)
        "src/lib/bookmarks.ts", // Bookmark feature module (used at runtime)
        "src/lib/supabase.ts", // Supabase client initialization (used at runtime)
        "src/components/entry/principal-parts.tsx", // Dynamic component loaded by route
      ],
      ignoreBinaries: [
        "supabase", // Supabase CLI, used for local dev and migrations
      ],
      project: "src/**/*.{ts,tsx}",
    },

    // lexico-components: Shared React component library (shadcn/ui)
    "packages/lexico-components": {
      // Shadcn-generated components, lib utilities, and hooks are managed by shadcn CLI
      // and may appear unused to knip but are consumed by lexico at runtime
      ignore: ["src/components/**", "src/lib/**", "src/hooks/**"],

      // Radix UI packages and other shadcn dependencies are installed by 'pnpx shadcn add'
      // and consumed by shadcn-generated components — knip can't trace these imports
      // because the component files are in the ignored src/components/ directory
      ignoreDependencies: [
        "@radix-ui/react-alert-dialog",
        "@radix-ui/react-aspect-ratio",
        "@radix-ui/react-avatar",
        "@radix-ui/react-checkbox",
        "@radix-ui/react-context-menu",
        "@radix-ui/react-dropdown-menu",
        "@radix-ui/react-hover-card",
        "@radix-ui/react-menubar",
        "@radix-ui/react-navigation-menu",
        "@radix-ui/react-popover",
        "@radix-ui/react-progress",
        "@radix-ui/react-radio-group",
        "@radix-ui/react-scroll-area",
        "@radix-ui/react-select",
        "@radix-ui/react-slider",
        "@radix-ui/react-switch",
        "@radix-ui/react-toggle",
        "@radix-ui/react-toggle-group",
        "cmdk", // Command menu component used by shadcn
        "embla-carousel-react", // Carousel component used by shadcn
        "input-otp", // OTP input component used by shadcn
        "next-themes", // Theme provider used by shadcn
        "react-day-picker", // Date picker component used by shadcn
        "react-hook-form", // Form handling used by shadcn form components
        "react-resizable-panels", // Resizable panel component used by shadcn
        "recharts", // Chart library used by shadcn chart components
        "sonner", // Toast notification component used by shadcn
        "vaul", // Drawer component used by shadcn
      ],
      project: "src/**/*.{ts,tsx}",
    },

    // code-generator: Nx generator plugin for scaffolding React components
    "tools/code-generator": {
      entry: "src/generators/*/generator.ts", // Each generator's entry point
      ignore: [
        "src/**/files/**", // Template files (EJS syntax, not valid TS)
        "src/**/*.test.ts",
      ],
      ignoreDependencies: [
        "react", // Peer dependency — consumed by generated components, not the generator itself
      ],
      project: "src/**/*.ts",
    },
  },
};

export default config;
