packages:
  - applications/*
  - packages/*
  - tools/*
allowBuilds:
  "@apollo/protobufjs": set this to true or false
  "@nestjs/core": true
  "@swc/core": true
  cpu-features: true
  esbuild: true
  nx: true
  protobufjs: true
  ssh2: true
  sweph: true
  unrs-resolver: true
