export { Entry } from "./entities/Entry.entity.js";
export { Translation } from "./entities/Translation.entity.js";
export { Word } from "./entities/Word.entity.js";
export type { PartOfSpeech } from "./entities/PartOfSpeech.js";
export { partOfSpeechValues } from "./entities/PartOfSpeech.js";
export { PrincipalPart } from "./entities/PrincipalPart.entity.js";
export { Pronunciation, PronunciationParts } from "./entities/Pronunciation.js";
export * from "./entities/inflection/index.js";
export * from "./entities/forms/index.js";
export { LexicoDatabaseModule } from "./database/lexico-database.module.js";
