name: ✨ Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please describe what
        you'd like and why it would be useful.

  # <!-- scopes-start -->
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which area of the monorepo does this apply to?
      options:
        - applications
        - caelundas
        - configuration
        - dependencies
        - deployments
        - documentation
        - infrastructure
        - JimmyPaolini
        - lexico
        - lexico-components
        - linting
        - monorepo
        - no-release
        - packages
        - release
        - scripts
        - testing
        - tools

    validations:
      required: true
  # <!-- scopes-end -->

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        What problem does this feature solve? Is it related to a
        frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Any other context, alternatives considered, mockups, or
        references.
    validations:
      required: false
