import moment from "moment-timezone";
import type { Choices } from "./choices.types";

export const initialChoices: Choices = {
  eventTypes: [
    "ingresses",
    "aspects",
    "retrogrades",
    "planetaryPhases",
    "annualSolarCycle",
    "monthlyLunarCycle",
    "dailySolarCycle",
    "dailyLunarCycle",
    "twilights",
  ],
  ingresses: [
    //
    "signs",
    "decans",
    "peaks",
  ],
  signIngressBodies: [
    "sun",
    "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  decanIngressBodies: [
    "sun",
    "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  peakIngressBodies: [
    "sun",
    "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  aspects: [
    //
    "majorAspects",
    "minorAspects",
    "specialtyAspects",
  ],
  majorAspectBodies: [
    "sun",
    // "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  minorAspectBodies: [
    "sun",
    // "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  specialtyAspectBodies: [
    "sun",
    // "moon",
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    "halley",
    "north lunar node",
    "lunar apogee",
  ],
  retrogradeBodies: [
    "mercury",
    "venus",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "chiron",
    "lilith",
    "ceres",
    "pallas",
    "juno",
    "vesta",
    // "lunar apogee",
  ],
  planetaryPhaseBodies: ["venus", "mercury", "mars"],
  /** @description Rittenhouse Square, southeast corner of the fountain */
  latitude: parseFloat(process.env.LATITUDE || "39.949309"),
  longitude: parseFloat(process.env.LONGITUDE || "-75.17169"),
  start: moment
    .tz(
      process.env.START_DATE || "2025-01-01",
      process.env.TIMEZONE || "America/New_York"
    )
    .toDate(),
  end: moment
    .tz(
      process.env.END_DATE || "2025-12-31",
      process.env.TIMEZONE || "America/New_York"
    )
    .toDate(),
};
