// ♟️ Constants

export const LITERATURE_CONSTANTS = {};

export const ROMAN_VALUES: Record<string, number> = {
  C: 100,
  D: 500,
  I: 1,
  L: 50,
  M: 1000,
  V: 5,
  X: 10,
};

export const authorIdToName: Record<string, string> = {
  ammianus: "ammianus marcellinus",
  apuleius: "lucius apuleius madaurensis",
  augustus: "caesar divi filius augustus",
  "aurelius-victor": "sextus aurelius victor",
  caesar: "gaius iulius caesar",
  cato: "marcus porcius cato censor",
  catullus: "gaius valerius catullus",
  cicero: "marcus tullius cicero",
  claudian: "claudius claudianus",
  "curtius-rufus": "quintus curtius rufus",
  ennius: "quintus ennius",
  eutropius: "eutropius",
  florus: "florus",
  frontinus: "sextus iulius frontinus",
  gellius: "aulus gellius",
  "historia-augusta": "scriptores historiae augustae",
  horace: "quintus horacius flaccus",
  justin: "marcus iunianus iustinus",
  juvenal: "decimus iunius iuvenalis",
  livy: "titus livius",
  lucan: "marcus annaeus lucanus",
  lucretius: "titus lucretius carus",
  martial: "marcus valerius martialis",
  nepos: "cornelius nepos",
  ovid: "publius ovidius naso",
  persius: "aulus persius flaccus",
  petronius: "gaius petronius",
  phaedrus: "phaedrus",
  plautus: "titus maccius plautus",
  "pliny-maior": "gaius plinius secundus",
  "pliny-minor": "gaius plinius caecilius secundus",
  propertius: "sextus propertius",
  quintilian: "marcus fabius quiintilianus",
  "roman-law": "ius romanum",
  sallust: "gaius sallustius crispus",
  "seneca-maior": "lucius annaeus seneca maior",
  "seneca-minor": "lucius annaeus seneca",
  "silius-italicus": "silius italicus",
  statius: "publius papinius statius",
  suetonius: "gaius suetonius tranquillus",
  sulpicia: "sulpicia",
  tacitus: "publius cornelius tacitus",
  terence: "publius terentius afer",
  tibullus: "albius tibullus",
  "valerius-flaccus": "gaius valereius flaccus",
  "valerius-maximus": "valerius maximus",
  varro: "marcus terentius varro",
  vellius: "gaius velleius patereculus",
  virgil: "publius vergilius maro",
  vitruvius: "marcus vitruvius pollio",
  "vulgate-bible-new-testament": "biblia sacra vulgata testamentum novum",
  "vulgate-bible-old-testament": "biblia sacra vulgata testamentum vetum",
};

export const bookNameMap: Record<string, string> = {
  "commentariorum libri iii de bello civili": "de bello civili",
  "commentariorum libri vii de bello gallicocum a. hirti supplemento":
    "de bello gallico",
  "libri incertorum auctorum": "",
};

export const worksMap: Record<string, string> = {
  aen: "aeneid",
  alex: "de bello alexandrino",
  amor: "amores",
  artis: "ars amatoria",
  bc: "de bello civili",
  bellafr: "de bello africo",
  ec: "eclogues",
  fasti: "fasti",
  gall: "de bello gallico",
  geo: "georgicon",
  her: "heroides",
  hisp: "de bello hispaniensi",
  ibis: "ibis",
  met: "metamorphoses",
  ponto: "ex ponto",
  pontoalone: "ponto",
  rem: "remedia amoris",
  resgestae: "res gestae divi augusti",
  tristia: "tristia",
};
