import { Module } from "@nestjs/common";

import { SampleDataLoader } from "./sample.dataloader";
import { SampleResolver } from "./sample.resolver";
import { SampleService } from "./sample.service";

/**
 * Sample GraphQL module — demonstrates the nestjs-graphql-module pattern.
 * Replace with your own domain modules generated by:
 *
 * ```bash
 * nx g conformance:nestjs-graphql-module --name=<domain>
 * ```
 */
@Module({
  exports: [SampleDataLoader, SampleService],
  imports: [],
  providers: [SampleDataLoader, SampleResolver, SampleService],
})
export class SampleModule {}
