# Default values for kubernetes-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: my-application
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Job-specific configuration
job:
  # Number of retries before considering a Job as failed
  backoffLimit: 3
  # Number of successful completions required
  completions: 1
  # Number of pods running in parallel
  parallelism: 1
  # Time in seconds after which a finished job is automatically deleted
  ttlSecondsAfterFinished: 86400

# Environment variables
env:
  []
  # - name: MY_ENV_VAR
  #   value: "my-value"
  # - name: SECRET_ENV_VAR
  #   valueFrom:
  #     secretKeyRef:
  #       name: my-secret
  #       key: secret-key

# Command and arguments override
command:
  []
  # - "/bin/sh"
args:
  []
  # - "-c"
  # - "echo hello"

persistence:
  enabled: true
  storageClassName: "standard"
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /app/data

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the
  # following lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
