"""Spiritual practice configuration: topics and affirmation grammatical structures."""

TAROT_CARDS = [
    {"name": "The Fool", "slug": "the-fool"},
    {"name": "The Magician", "slug": "the-magician"},
    {"name": "The High Priestess", "slug": "the-high-priestess"},
    {"name": "The Empress", "slug": "the-empress"},
    {"name": "The Emperor", "slug": "the-emperor"},
    {"name": "The Hierophant", "slug": "the-hierophant"},
    {"name": "The Lovers", "slug": "the-lovers"},
    {"name": "The Chariot", "slug": "the-chariot"},
    {"name": "Strength", "slug": "strength"},
    {"name": "The Hermit", "slug": "the-hermit"},
    {"name": "Wheel of Fortune", "slug": "wheel-of-fortune"},
    {"name": "Justice", "slug": "justice"},
    {"name": "The Hanged Man", "slug": "the-hanged-man"},
    {"name": "Death", "slug": "death"},
    {"name": "Temperance", "slug": "temperance"},
    {"name": "The Devil", "slug": "the-devil"},
    {"name": "The Tower", "slug": "the-tower"},
    {"name": "The Star", "slug": "the-star"},
    {"name": "The Moon", "slug": "the-moon"},
    {"name": "The Sun", "slug": "the-sun"},
    {"name": "Judgment", "slug": "judgment"},
    {"name": "The World", "slug": "the-world"},
    {"name": "The Ace of Wands", "slug": "the-ace-of-wands"},
    {"name": "The Two of Wands", "slug": "the-two-of-wands"},
    {"name": "The Three of Wands", "slug": "the-three-of-wands"},
    {"name": "The Four of Wands", "slug": "the-four-of-wands"},
    {"name": "The Five of Wands", "slug": "the-five-of-wands"},
    {"name": "The Six of Wands", "slug": "the-six-of-wands"},
    {"name": "The Seven of Wands", "slug": "the-seven-of-wands"},
    {"name": "The Eight of Wands", "slug": "the-eight-of-wands"},
    {"name": "The Nine of Wands", "slug": "the-nine-of-wands"},
    {"name": "The Ten of Wands", "slug": "the-ten-of-wands"},
    {"name": "The Page of Wands", "slug": "the-page-of-wands"},
    {"name": "The Knight of Wands", "slug": "the-knight-of-wands"},
    {"name": "The Queen of Wands", "slug": "the-queen-of-wands"},
    {"name": "The King of Wands", "slug": "the-king-of-wands"},
    {"name": "The Ace of Cups", "slug": "the-ace-of-cups"},
    {"name": "The Two of Cups", "slug": "the-two-of-cups"},
    {"name": "The Three of Cups", "slug": "the-three-of-cups"},
    {"name": "The Four of Cups", "slug": "the-four-of-cups"},
    {"name": "The Five of Cups", "slug": "the-five-of-cups"},
    {"name": "The Six of Cups", "slug": "the-six-of-cups"},
    {"name": "The Seven of Cups", "slug": "the-seven-of-cups"},
    {"name": "The Eight of Cups", "slug": "the-eight-of-cups"},
    {"name": "The Nine of Cups", "slug": "the-nine-of-cups"},
    {"name": "The Ten of Cups", "slug": "the-ten-of-cups"},
    {"name": "The Page of Cups", "slug": "the-page-of-cups"},
    {"name": "The Knight of Cups", "slug": "the-knight-of-cups"},
    {"name": "The Queen of Cups", "slug": "the-queen-of-cups"},
    {"name": "The King of Cups", "slug": "the-king-of-cups"},
    {"name": "The Ace of Swords", "slug": "the-ace-of-swords"},
    {"name": "The Two of Swords", "slug": "the-two-of-swords"},
    {"name": "The Three of Swords", "slug": "the-three-of-swords"},
    {"name": "The Four of Swords", "slug": "the-four-of-swords"},
    {"name": "The Five of Swords", "slug": "the-five-of-swords"},
    {"name": "The Six of Swords", "slug": "the-six-of-swords"},
    {"name": "The Seven of Swords", "slug": "the-seven-of-swords"},
    {"name": "The Eight of Swords", "slug": "the-eight-of-swords"},
    {"name": "The Nine of Swords", "slug": "the-nine-of-swords"},
    {"name": "The Ten of Swords", "slug": "the-ten-of-swords"},
    {"name": "The Page of Swords", "slug": "the-page-of-swords"},
    {"name": "The Knight of Swords", "slug": "the-knight-of-swords"},
    {"name": "The Queen of Swords", "slug": "the-queen-of-swords"},
    {"name": "The King of Swords", "slug": "the-king-of-swords"},
    {"name": "The Ace of Pentacles", "slug": "the-ace-of-pentacles"},
    {"name": "The Two of Pentacles", "slug": "the-two-of-pentacles"},
    {"name": "The Three of Pentacles", "slug": "the-three-of-pentacles"},
    {"name": "The Four of Pentacles", "slug": "the-four-of-pentacles"},
    {"name": "The Five of Pentacles", "slug": "the-five-of-pentacles"},
    {"name": "The Six of Pentacles", "slug": "the-six-of-pentacles"},
    {"name": "The Seven of Pentacles", "slug": "the-seven-of-pentacles"},
    {"name": "The Eight of Pentacles", "slug": "the-eight-of-pentacles"},
    {"name": "The Nine of Pentacles", "slug": "the-nine-of-pentacles"},
    {"name": "The Ten of Pentacles", "slug": "the-ten-of-pentacles"},
    {"name": "The Page of Pentacles", "slug": "the-page-of-pentacles"},
    {"name": "The Knight of Pentacles", "slug": "the-knight-of-pentacles"},
    {"name": "The Queen of Pentacles", "slug": "the-queen-of-pentacles"},
    {"name": "The King of Pentacles", "slug": "the-king-of-pentacles"},
]

LENORMAND_CARDS = [
    {"name": "Rider", "slug": "rider"},
    {"name": "Clover", "slug": "clover"},
    {"name": "Ship", "slug": "ship"},
    {"name": "House", "slug": "house"},
    {"name": "Tree", "slug": "tree"},
    {"name": "Clouds", "slug": "clouds"},
    {"name": "Snake", "slug": "snake"},
    {"name": "Coffin", "slug": "coffin"},
    {"name": "Bouquet", "slug": "bouquet"},
    {"name": "Scythe", "slug": "scythe"},
    {"name": "Whip", "slug": "whip"},
    {"name": "Birds", "slug": "birds"},
    {"name": "Child", "slug": "child"},
    {"name": "Fox", "slug": "fox"},
    {"name": "Bear", "slug": "bear"},
    {"name": "Stars", "slug": "stars"},
    {"name": "Stork", "slug": "stork"},
    {"name": "Dog", "slug": "dog"},
    {"name": "Tower", "slug": "tower"},
    {"name": "Garden", "slug": "garden"},
    {"name": "Mountain", "slug": "mountain"},
    {"name": "Crossroads", "slug": "crossroads"},
    {"name": "Mice", "slug": "mice"},
    {"name": "Heart", "slug": "heart"},
    {"name": "Ring", "slug": "ring"},
    {"name": "Book", "slug": "book"},
    {"name": "Letter", "slug": "letter"},
    {"name": "Man", "slug": "man"},
    {"name": "Gentleman", "slug": "gentleman"},
    {"name": "Woman", "slug": "woman"},
    {"name": "Lady", "slug": "lady"},
    {"name": "Lily", "slug": "lily"},
    {"name": "Sun", "slug": "sun"},
    {"name": "Moon", "slug": "moon"},
    {"name": "Key", "slug": "key"},
    {"name": "Fish", "slug": "fish"},
    {"name": "Anchor", "slug": "anchor"},
    {"name": "Cross", "slug": "cross"},
]

ASTROLOGY_SIGNS = [
    {"name": "Aries", "slug": "aries"},
    {"name": "Taurus", "slug": "taurus"},
    {"name": "Gemini", "slug": "gemini"},
    {"name": "Cancer", "slug": "cancer"},
    {"name": "Leo", "slug": "leo"},
    {"name": "Virgo", "slug": "virgo"},
    {"name": "Libra", "slug": "libra"},
    {"name": "Scorpio", "slug": "scorpio"},
    {"name": "Sagittarius", "slug": "sagittarius"},
    {"name": "Capricorn", "slug": "capricorn"},
    {"name": "Aquarius", "slug": "aquarius"},
    {"name": "Pisces", "slug": "pisces"},
]

ASTROLOGY_PLANETS = [
    {"name": "Sun", "slug": "sun"},
    {"name": "Moon", "slug": "moon"},
    {"name": "Mercury", "slug": "mercury"},
    {"name": "Venus", "slug": "venus"},
    {"name": "Mars", "slug": "mars"},
    {"name": "Jupiter", "slug": "jupiter"},
    {"name": "Saturn", "slug": "saturn"},
    {"name": "Uranus", "slug": "uranus"},
    {"name": "Neptune", "slug": "neptune"},
    {"name": "Pluto", "slug": "pluto"},
]

ASTROLOGY_ASTEROIDS = [
    {"name": "Chiron", "slug": "chiron"},
    {"name": "Lilith", "slug": "lilith"},
    {"name": "Ceres", "slug": "ceres"},
    {"name": "Pallas", "slug": "pallas"},
    {"name": "Juno", "slug": "juno"},
    {"name": "Vesta", "slug": "vesta"},
]

ASTROLOGY_HOUSES = [
    {"name": "First House (Ascendant)", "slug": "first-house"},
    {"name": "Second House", "slug": "second-house"},
    {"name": "Third House", "slug": "third-house"},
    {"name": "Fourth House (Imum Coeli)", "slug": "fourth-house"},
    {"name": "Fifth House", "slug": "fifth-house"},
    {"name": "Sixth House", "slug": "sixth-house"},
    {"name": "Seventh House (Descendant)", "slug": "seventh-house"},
    {"name": "Eighth House", "slug": "eighth-house"},
    {"name": "Ninth House", "slug": "ninth-house"},
    {"name": "Tenth House (Medium Coeli)", "slug": "tenth-house"},
    {"name": "Eleventh House", "slug": "eleventh-house"},
    {"name": "Twelfth House", "slug": "twelfth-house"},
]

ASTROLOGY_MODALITIES = [
    {"name": "Cardinal", "slug": "cardinal"},
    {"name": "Fixed", "slug": "fixed"},
    {"name": "Mutable", "slug": "mutable"},
]

POLARITIES = [
    {"name": "Positive", "slug": "positive"},
    {"name": "Negative", "slug": "negative"},
]

ASTROLOGY_ASPECTS = [
    {"name": "Conjunction", "slug": "conjunction"},
    {"name": "Sextile", "slug": "sextile"},
    {"name": "Square", "slug": "square"},
    {"name": "Trine", "slug": "trine"},
    {"name": "Opposition", "slug": "opposition"},
    {"name": "Quincunx", "slug": "quincunx"},
    {"name": "Semisextile", "slug": "semisextile"},
    {"name": "Semisquare", "slug": "semisquare"},
    {"name": "Sesquiquadrate", "slug": "sesquiquadrate"},
    {"name": "Quintile", "slug": "quintile"},
    {"name": "Biquintile", "slug": "biquintile"},
    {"name": "Novile", "slug": "novile"},
    {"name": "Binovile", "slug": "binovile"},
    {"name": "Tredecile", "slug": "tredecile"},
    {"name": "Septile", "slug": "septile"},
    {"name": "Biseptile", "slug": "biseptile"},
    {"name": "Tredecile", "slug": "tredicile"},
]

CHAKRAS = [
    {"name": "Root Chakra (Muladhara)", "slug": "root"},
    {"name": "Sacral Chakra (Svadhisthana)", "slug": "sacral"},
    {"name": "Solar Plexus Chakra (Manipura)", "slug": "solar-plexus"},
    {"name": "Heart Chakra (Anahata)", "slug": "heart"},
    {"name": "Throat Chakra (Vishuddha)", "slug": "throat"},
    {"name": "Third Eye Chakra (Ajna)", "slug": "third-eye"},
    {"name": "Crown Chakra (Sahasrara)", "slug": "crown"},
]

RUNES = [
    {"name": "Fehu (Wealth)", "slug": "fehu"},
    {"name": "Uruz (Strength)", "slug": "uruz"},
    {"name": "Thurisaz (Protection)", "slug": "thurisaz"},
    {"name": "Ansuz (Wisdom)", "slug": "ansuz"},
    {"name": "Raidho (Journey)", "slug": "raidho"},
    {"name": "Kenaz (Knowledge)", "slug": "kenaz"},
    {"name": "Gebo (Partnership)", "slug": "gebo"},
    {"name": "Wunjo (Joy)", "slug": "wunjo"},
    {"name": "Hagalaz (Transformation)", "slug": "hagalaz"},
    {"name": "Nauthiz (Need)", "slug": "nauthiz"},
    {"name": "Isa (Stillness)", "slug": "isa"},
    {"name": "Jera (Harvest)", "slug": "jera"},
    {"name": "Eihwaz (Connection)", "slug": "eihwaz"},
    {"name": "Perth (Mystery)", "slug": "perth"},
    {"name": "Algiz (Protection)", "slug": "algiz"},
    {"name": "Sowilo (Success)", "slug": "sowilo"},
    {"name": "Tiwaz (Victory)", "slug": "tiwaz"},
    {"name": "Berkano (Growth)", "slug": "berkano"},
    {"name": "Ehwaz (Movement)", "slug": "ehwaz"},
    {"name": "Mannaz (Humanity)", "slug": "mannaz"},
    {"name": "Laguz (Flow)", "slug": "laguz"},
    {"name": "Ingwaz (Potential)", "slug": "ingwaz"},
    {"name": "Dagaz (Breakthrough)", "slug": "dagaz"},
    {"name": "Othala (Heritage)", "slug": "othala"},
]

SEPHIROT = [
    {"name": "Kether (Crown)", "slug": "kether"},
    {"name": "Chokmah (Wisdom)", "slug": "chokmah"},
    {"name": "Binah (Understanding)", "slug": "binah"},
    {"name": "Chesed (Mercy)", "slug": "chesed"},
    {"name": "Geburah (Strength)", "slug": "geburah"},
    {"name": "Tiphareth (Beauty)", "slug": "tiphareth"},
    {"name": "Netzach (Victory)", "slug": "netzach"},
    {"name": "Hod (Splendor)", "slug": "hod"},
    {"name": "Yesod (Foundation)", "slug": "yesod"},
    {"name": "Malkuth (Kingdom)", "slug": "malkuth"},
]

HEBREW_LETTERS = [
    {"name": "Aleph", "slug": "aleph", "letter": "א"},
    {"name": "Beth", "slug": "beth", "letter": "ב"},
    {"name": "Gimel", "slug": "gimel", "letter": "ג"},
    {"name": "Daleth", "slug": "daleth", "letter": "ד"},
    {"name": "He", "slug": "he", "letter": "ה"},
    {"name": "Vav", "slug": "vav", "letter": "ו"},
    {"name": "Zayin", "slug": "zayin", "letter": "ז"},
    {"name": "Chet", "slug": "chet", "letter": "ח"},
    {"name": "Tet", "slug": "tet", "letter": "ט"},
    {"name": "Yod", "slug": "yod", "letter": "י"},
    {"name": "Kaf", "slug": "kaf", "letter": "כ"},
    {"name": "Lamed", "slug": "lamed", "letter": "ל"},
    {"name": "Mem", "slug": "mem", "letter": "מ"},
    {"name": "Nun", "slug": "nun", "letter": "נ"},
    {"name": "Samekh", "slug": "samekh", "letter": "ס"},
    {"name": "Ayin", "slug": "ayin", "letter": "ע"},
    {"name": "Pe", "slug": "pe", "letter": "פ"},
    {"name": "Tsadi", "slug": "tsadi", "letter": "צ"},
    {"name": "Qof", "slug": "qof", "letter": "ק"},
    {"name": "Resh", "slug": "resh", "letter": "ר"},
    {"name": "Shin", "slug": "shin", "letter": "ש"},
    {"name": "Tav", "slug": "tav", "letter": "ת"},
]

KABBALAH_WORLDS = [
    {"name": "Atziluth (Emanation)", "slug": "atziluth"},
    {"name": "Briah (Creation)", "slug": "briah"},
    {"name": "Yetzirah (Formation)", "slug": "yetzirah"},
    {"name": "Assiah (Action)", "slug": "assiah"},
]

SOLFEGGIOS = [
    {"name": "Do", "slug": "do"},
    {"name": "Re", "slug": "re"},
    {"name": "Mi", "slug": "mi"},
    {"name": "Fa", "slug": "fa"},
    {"name": "Sol", "slug": "sol"},
    {"name": "La", "slug": "la"},
    {"name": "Ti", "slug": "ti"},
]

WEEKDAYS = [
    {"name": "Monday", "slug": "monday"},
    {"name": "Tuesday", "slug": "tuesday"},
    {"name": "Wednesday", "slug": "wednesday"},
    {"name": "Thursday", "slug": "thursday"},
    {"name": "Friday", "slug": "friday"},
    {"name": "Saturday", "slug": "saturday"},
    {"name": "Sunday", "slug": "sunday"},
]

ELEMENTS = [
    {"name": "Earth", "slug": "earth"},
    {"name": "Air", "slug": "air"},
    {"name": "Fire", "slug": "fire"},
    {"name": "Water", "slug": "water"},
]

COLORS = [
    {"name": "Black", "slug": "black"},
    {"name": "White", "slug": "white"},
    {"name": "Red", "slug": "red"},
    {"name": "Orange", "slug": "orange"},
    {"name": "Yellow", "slug": "yellow"},
    {"name": "Green", "slug": "green"},
    {"name": "Blue", "slug": "blue"},
    {"name": "Indigo", "slug": "indigo"},
    {"name": "Violet", "slug": "violet"},
    {"name": "Pink", "slug": "pink"},
    {"name": "Brown", "slug": "brown"},
    {"name": "Gray", "slug": "gray"},
]

GEMSTONES = [
    {"name": "Garnet", "slug": "garnet"},
    {"name": "Amethyst", "slug": "amethyst"},
    {"name": "Aquamarine", "slug": "aquamarine"},
    {"name": "Diamond", "slug": "diamond"},
    {"name": "Emerald", "slug": "emerald"},
    {"name": "Pearl", "slug": "pearl"},
    {"name": "Ruby", "slug": "ruby"},
    {"name": "Peridot", "slug": "peridot"},
    {"name": "Sapphire", "slug": "sapphire"},
    {"name": "Opal", "slug": "opal"},
    {"name": "Topaz", "slug": "topaz"},
    {"name": "Turquoise", "slug": "turquoise"},
]

METALS = [
    {"name": "Gold", "slug": "gold"},
    {"name": "Mercury", "slug": "mercury"},
    {"name": "Copper", "slug": "copper"},
    {"name": "Silver", "slug": "silver"},
    {"name": "Iron", "slug": "iron"},
    {"name": "Tin", "slug": "tin"},
    {"name": "Lead", "slug": "lead"},
]

NUMBERS = [
    {"name": "One", "slug": "one"},
    {"name": "Two", "slug": "two"},
    {"name": "Three", "slug": "three"},
    {"name": "Four", "slug": "four"},
    {"name": "Five", "slug": "five"},
    {"name": "Six", "slug": "six"},
    {"name": "Seven", "slug": "seven"},
    {"name": "Eight", "slug": "eight"},
    {"name": "Nine", "slug": "nine"},
    {"name": "Ten", "slug": "ten"},
    {"name": "Eleven", "slug": "eleven"},
    {"name": "Twelve", "slug": "twelve"},
    {"name": "Thirteen", "slug": "thirteen"},
    {"name": "Fourteen", "slug": "fourteen"},
    {"name": "Fifteen", "slug": "fifteen"},
    {"name": "Sixteen", "slug": "sixteen"},
    {"name": "Seventeen", "slug": "seventeen"},
    {"name": "Eighteen", "slug": "eighteen"},
    {"name": "Nineteen", "slug": "nineteen"},
    {"name": "Twenty", "slug": "twenty"},
    {"name": "Twenty One", "slug": "twenty-one"},
    {"name": "Twenty Two", "slug": "twenty-two"},
    {"name": "Twenty Three", "slug": "twenty-three"},
    {"name": "Twenty Four", "slug": "twenty-four"},
    {"name": "Twenty Five", "slug": "twenty-five"},
    {"name": "Twenty Six", "slug": "twenty-six"},
    {"name": "Twenty Seven", "slug": "twenty-seven"},
    {"name": "Twenty Eight", "slug": "twenty-eight"},
    {"name": "Twenty Nine", "slug": "twenty-nine"},
    {"name": "Thirty", "slug": "thirty"},
    {"name": "Thirty One", "slug": "thirty-one"},
    {"name": "Thirty Two", "slug": "thirty-two"},
]
