"""Spiritual practice configuration: topics and affirmation grammatical structures."""

from pydantic import BaseModel, Field


class PracticeConfig(BaseModel):
    """Configuration for a single spiritual practice."""

    name: str = Field(description="Practice name (lowercase kebab-case)")
    topics: list[str] = Field(
        description="List of topics/elements within this practice",
        min_length=1,
    )
    structures: list[str] = Field(
        description="Grammatical structures for affirmations in this practice",
        min_length=1,
    )


PRACTICES: dict[str, PracticeConfig] = {
    "tarot": PracticeConfig(
        name="tarot",
        topics=[
            "The Fool",
            "The Magician",
            "The High Priestess",
            "The Empress",
            "The Emperor",
            "The Hierophant",
            "The Lovers",
            "The Chariot",
            "Strength",
            "The Hermit",
            "Wheel of Fortune",
            "Justice",
            "The Hanged Man",
            "Death",
            "Temperance",
            "The Devil",
            "The Tower",
            "The Star",
            "The Moon",
            "The Sun",
            "Judgment",
            "The World",
        ],
        structures=[
            "I am [positive quality] through [transformative process]",
            "I embrace [symbolic theme] and [positive outcome]",
            "Through [archetype energy], I [empowering action]",
            "I release [limiting belief] and step into [new possibility]",
        ],
    ),
    "astrology": PracticeConfig(
        name="astrology",
        topics=[
            "Aries",
            "Taurus",
            "Gemini",
            "Cancer",
            "Leo",
            "Virgo",
            "Libra",
            "Scorpio",
            "Sagittarius",
            "Capricorn",
            "Aquarius",
            "Pisces",
        ],
        structures=[
            "I channel the [zodiac quality] energy of [sign] to [positive action]",
            "As a [sign], I am gifted with [natural strength]",
            "I align with [planetary ruler] and [positive manifestation]",
            "My [sign] nature empowers me to [empowering action]",
        ],
    ),
    "chakras": PracticeConfig(
        name="chakras",
        topics=[
            "Root Chakra (Muladhara)",
            "Sacral Chakra (Svadhisthana)",
            "Solar Plexus Chakra (Manipura)",
            "Heart Chakra (Anahata)",
            "Throat Chakra (Vishuddha)",
            "Third Eye Chakra (Ajna)",
            "Crown Chakra (Sahasrara)",
        ],
        structures=[
            "My [chakra name] is open and [positive quality] flows freely",
            "I am grounded in [chakra energy] and [positive state]",
            "I activate my [chakra name] by [empowering practice]",
            "Through [chakra element], I [positive transformation]",
        ],
    ),
    "kabbalah": PracticeConfig(
        name="kabbalah",
        topics=[
            "Kether (Crown)",
            "Chokmah (Wisdom)",
            "Binah (Understanding)",
            "Chesed (Mercy)",
            "Geburah (Strength)",
            "Tiphareth (Beauty)",
            "Netzach (Victory)",
            "Hod (Splendor)",
            "Yesod (Foundation)",
            "Malkuth (Kingdom)",
        ],
        structures=[
            "I embody the [sephirah quality] of [sephirah name] in all I do",
            "Through [sephirah energy], I [spiritual action]",
            "I am a vessel for [divine attribute] as expressed through [sephirah]",
        ],
    ),
    "runes": PracticeConfig(
        name="runes",
        topics=[
            "Fehu (Wealth)",
            "Uruz (Strength)",
            "Thurisaz (Protection)",
            "Ansuz (Wisdom)",
            "Raidho (Journey)",
            "Kenaz (Knowledge)",
            "Gebo (Partnership)",
            "Wunjo (Joy)",
            "Hagalaz (Transformation)",
            "Nauthiz (Need)",
            "Isa (Stillness)",
            "Jera (Harvest)",
            "Eihwaz (Connection)",
            "Perth (Mystery)",
            "Algiz (Protection)",
            "Sowilo (Success)",
            "Tiwaz (Victory)",
            "Berkano (Growth)",
            "Ehwaz (Movement)",
            "Mannaz (Humanity)",
            "Laguz (Flow)",
            "Ingwaz (Potential)",
            "Dagaz (Breakthrough)",
            "Othala (Heritage)",
        ],
        structures=[
            "I carry the power of [rune name] and [associated quality]",
            "Through [rune energy], I [positive manifestation]",
            "I am guided by [rune meaning] on my path to [positive goal]",
        ],
    ),
    "lenormand": PracticeConfig(
        name="lenormand",
        topics=[
            "The Rider",
            "The Clover",
            "The Ship",
            "The House",
            "The Tree",
            "The Clouds",
            "The Snake",
            "The Coffin",
            "The Bouquet",
            "The Scythe",
            "The Whip",
            "The Birds",
            "The Child",
            "The Fox",
            "The Bear",
            "The Stars",
            "The Storks",
            "The Dog",
            "The Tower",
            "The Garden",
            "The Mountain",
            "The Crossroads",
            "The Mice",
            "The Heart",
            "The Ring",
            "The Book",
            "The Letter",
            "The Man",
            "The Woman",
            "The Lily",
            "The Sun",
            "The Moon",
            "The Key",
            "The Fish",
            "The Anchor",
            "The Cross",
        ],
        structures=[
            "I welcome [card meaning] into my life with [positive quality]",
            "Through [card symbol], I [positive action or transformation]",
            "I am open to [card energy] guiding me toward [positive outcome]",
        ],
    ),
}
