"""Spiritual practice configuration: topics and affirmation grammatical structures."""

TAROT_CARDS = [
    {
        "name": "The Fool",
        "slug": "the-fool",
        "order": 0,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Magician",
        "slug": "the-magician",
        "order": 1,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The High Priestess",
        "slug": "the-high-priestess",
        "order": 2,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Empress",
        "slug": "the-empress",
        "order": 3,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Emperor",
        "slug": "the-emperor",
        "order": 4,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Hierophant",
        "slug": "the-hierophant",
        "order": 5,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Lovers",
        "slug": "the-lovers",
        "order": 6,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Chariot",
        "slug": "the-chariot",
        "order": 7,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "Strength",
        "slug": "strength",
        "order": 8,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Hermit",
        "slug": "the-hermit",
        "order": 9,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "Wheel of Fortune",
        "slug": "wheel-of-fortune",
        "order": 10,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "Justice",
        "slug": "justice",
        "order": 11,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Hanged Man",
        "slug": "the-hanged-man",
        "order": 12,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "Death",
        "slug": "death",
        "order": 13,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "Temperance",
        "slug": "temperance",
        "order": 14,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Devil",
        "slug": "the-devil",
        "order": 15,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Tower",
        "slug": "the-tower",
        "order": 16,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Star",
        "slug": "the-star",
        "order": 17,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Moon",
        "slug": "the-moon",
        "order": 18,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Sun",
        "slug": "the-sun",
        "order": 19,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "Judgment",
        "slug": "judgment",
        "order": 20,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The World",
        "slug": "the-world",
        "order": 21,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Ace of Wands",
        "slug": "the-ace-of-wands",
        "order": 22,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Two of Wands",
        "slug": "the-two-of-wands",
        "order": 23,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Three of Wands",
        "slug": "the-three-of-wands",
        "order": 24,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Four of Wands",
        "slug": "the-four-of-wands",
        "order": 25,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Five of Wands",
        "slug": "the-five-of-wands",
        "order": 26,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Six of Wands",
        "slug": "the-six-of-wands",
        "order": 27,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Seven of Wands",
        "slug": "the-seven-of-wands",
        "order": 28,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Eight of Wands",
        "slug": "the-eight-of-wands",
        "order": 29,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Nine of Wands",
        "slug": "the-nine-of-wands",
        "order": 30,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Ten of Wands",
        "slug": "the-ten-of-wands",
        "order": 31,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Page of Wands",
        "slug": "the-page-of-wands",
        "order": 32,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Knight of Wands",
        "slug": "the-knight-of-wands",
        "order": 33,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Queen of Wands",
        "slug": "the-queen-of-wands",
        "order": 34,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The King of Wands",
        "slug": "the-king-of-wands",
        "order": 35,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Ace of Cups",
        "slug": "the-ace-of-cups",
        "order": 36,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Two of Cups",
        "slug": "the-two-of-cups",
        "order": 37,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Three of Cups",
        "slug": "the-three-of-cups",
        "order": 38,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Four of Cups",
        "slug": "the-four-of-cups",
        "order": 39,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Five of Cups",
        "slug": "the-five-of-cups",
        "order": 40,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Six of Cups",
        "slug": "the-six-of-cups",
        "order": 41,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Seven of Cups",
        "slug": "the-seven-of-cups",
        "order": 42,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Eight of Cups",
        "slug": "the-eight-of-cups",
        "order": 43,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Nine of Cups",
        "slug": "the-nine-of-cups",
        "order": 44,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Ten of Cups",
        "slug": "the-ten-of-cups",
        "order": 45,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Page of Cups",
        "slug": "the-page-of-cups",
        "order": 46,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Knight of Cups",
        "slug": "the-knight-of-cups",
        "order": 47,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Queen of Cups",
        "slug": "the-queen-of-cups",
        "order": 48,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The King of Cups",
        "slug": "the-king-of-cups",
        "order": 49,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Ace of Swords",
        "slug": "the-ace-of-swords",
        "order": 50,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Two of Swords",
        "slug": "the-two-of-swords",
        "order": 51,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Three of Swords",
        "slug": "the-three-of-swords",
        "order": 52,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Four of Swords",
        "slug": "the-four-of-swords",
        "order": 53,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Five of Swords",
        "slug": "the-five-of-swords",
        "order": 54,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Six of Swords",
        "slug": "the-six-of-swords",
        "order": 55,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Seven of Swords",
        "slug": "the-seven-of-swords",
        "order": 56,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Eight of Swords",
        "slug": "the-eight-of-swords",
        "order": 57,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Nine of Swords",
        "slug": "the-nine-of-swords",
        "order": 58,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Ten of Swords",
        "slug": "the-ten-of-swords",
        "order": 59,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Page of Swords",
        "slug": "the-page-of-swords",
        "order": 60,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Knight of Swords",
        "slug": "the-knight-of-swords",
        "order": 61,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Queen of Swords",
        "slug": "the-queen-of-swords",
        "order": 62,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The King of Swords",
        "slug": "the-king-of-swords",
        "order": 63,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Ace of Pentacles",
        "slug": "the-ace-of-pentacles",
        "order": 64,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Two of Pentacles",
        "slug": "the-two-of-pentacles",
        "order": 65,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Three of Pentacles",
        "slug": "the-three-of-pentacles",
        "order": 66,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Four of Pentacles",
        "slug": "the-four-of-pentacles",
        "order": 67,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Five of Pentacles",
        "slug": "the-five-of-pentacles",
        "order": 68,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Six of Pentacles",
        "slug": "the-six-of-pentacles",
        "order": 69,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Seven of Pentacles",
        "slug": "the-seven-of-pentacles",
        "order": 70,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Eight of Pentacles",
        "slug": "the-eight-of-pentacles",
        "order": 71,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Nine of Pentacles",
        "slug": "the-nine-of-pentacles",
        "order": 72,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Ten of Pentacles",
        "slug": "the-ten-of-pentacles",
        "order": 73,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Page of Pentacles",
        "slug": "the-page-of-pentacles",
        "order": 74,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Knight of Pentacles",
        "slug": "the-knight-of-pentacles",
        "order": 75,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The Queen of Pentacles",
        "slug": "the-queen-of-pentacles",
        "order": 76,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
    {
        "name": "The King of Pentacles",
        "slug": "the-king-of-pentacles",
        "order": 77,
        "category": {"name": "Tarot Card", "slug": "tarot-card"},
    },
]

LENORMAND_CARDS = [
    {
        "name": "Rider",
        "slug": "rider",
        "order": 1,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Clover",
        "slug": "clover",
        "order": 2,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Ship",
        "slug": "ship",
        "order": 3,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "House",
        "slug": "house",
        "order": 4,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Tree",
        "slug": "tree",
        "order": 5,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Clouds",
        "slug": "clouds",
        "order": 6,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Snake",
        "slug": "snake",
        "order": 7,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Coffin",
        "slug": "coffin",
        "order": 8,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Bouquet",
        "slug": "bouquet",
        "order": 9,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Scythe",
        "slug": "scythe",
        "order": 10,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Whip",
        "slug": "whip",
        "order": 11,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Birds",
        "slug": "birds",
        "order": 12,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Child",
        "slug": "child",
        "order": 13,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Fox",
        "slug": "fox",
        "order": 14,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Bear",
        "slug": "bear",
        "order": 15,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Stars",
        "slug": "stars",
        "order": 16,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Stork",
        "slug": "stork",
        "order": 17,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Dog",
        "slug": "dog",
        "order": 18,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Tower",
        "slug": "tower",
        "order": 19,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Garden",
        "slug": "garden",
        "order": 20,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Mountain",
        "slug": "mountain",
        "order": 21,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Crossroads",
        "slug": "crossroads",
        "order": 22,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Mice",
        "slug": "mice",
        "order": 23,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Heart",
        "slug": "heart",
        "order": 24,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Ring",
        "slug": "ring",
        "order": 25,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Book",
        "slug": "book",
        "order": 26,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Letter",
        "slug": "letter",
        "order": 27,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Man",
        "slug": "man",
        "order": 28,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Gentleman",
        "slug": "gentleman",
        "order": 29,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Woman",
        "slug": "woman",
        "order": 30,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Lady",
        "slug": "lady",
        "order": 31,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Lily",
        "slug": "lily",
        "order": 32,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Sun",
        "slug": "sun",
        "order": 33,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Moon",
        "slug": "moon",
        "order": 34,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Key",
        "slug": "key",
        "order": 35,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Fish",
        "slug": "fish",
        "order": 36,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Anchor",
        "slug": "anchor",
        "order": 37,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
    {
        "name": "Cross",
        "slug": "cross",
        "order": 38,
        "category": {"name": "Lenormand", "slug": "lenormand"},
    },
]

ASTROLOGY_SIGNS = [
    {
        "name": "Aries",
        "slug": "aries",
        "order": 1,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Taurus",
        "slug": "taurus",
        "order": 2,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Gemini",
        "slug": "gemini",
        "order": 3,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Cancer",
        "slug": "cancer",
        "order": 4,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Leo",
        "slug": "leo",
        "order": 5,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Virgo",
        "slug": "virgo",
        "order": 6,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Libra",
        "slug": "libra",
        "order": 7,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Scorpio",
        "slug": "scorpio",
        "order": 8,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Sagittarius",
        "slug": "sagittarius",
        "order": 9,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Capricorn",
        "slug": "capricorn",
        "order": 10,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Aquarius",
        "slug": "aquarius",
        "order": 11,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
    {
        "name": "Pisces",
        "slug": "pisces",
        "order": 12,
        "category": {"name": "Astrology Sign", "slug": "astrology-sign"},
    },
]

ASTROLOGY_PLANETS = [
    {
        "name": "Sun",
        "slug": "sun",
        "order": 1,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
    {
        "name": "Moon",
        "slug": "moon",
        "order": 2,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
    {
        "name": "Mercury",
        "slug": "mercury",
        "order": 3,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
    {
        "name": "Venus",
        "slug": "venus",
        "order": 4,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
    {
        "name": "Mars",
        "slug": "mars",
        "order": 5,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
    {
        "name": "Jupiter",
        "slug": "jupiter",
        "order": 6,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
    {
        "name": "Saturn",
        "slug": "saturn",
        "order": 7,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
    {
        "name": "Uranus",
        "slug": "uranus",
        "order": 8,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
    {
        "name": "Neptune",
        "slug": "neptune",
        "order": 9,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
    {
        "name": "Pluto",
        "slug": "pluto",
        "order": 10,
        "category": {"name": "Astrology Planet", "slug": "astrology-planet"},
    },
]

ASTROLOGY_ASTEROIDS = [
    {
        "name": "Chiron",
        "slug": "chiron",
        "order": 1,
        "category": {"name": "Astrology Asteroid", "slug": "astrology-asteroid"},
    },
    {
        "name": "Lilith",
        "slug": "lilith",
        "order": 2,
        "category": {"name": "Astrology Asteroid", "slug": "astrology-asteroid"},
    },
    {
        "name": "Ceres",
        "slug": "ceres",
        "order": 3,
        "category": {"name": "Astrology Asteroid", "slug": "astrology-asteroid"},
    },
    {
        "name": "Pallas",
        "slug": "pallas",
        "order": 4,
        "category": {"name": "Astrology Asteroid", "slug": "astrology-asteroid"},
    },
    {
        "name": "Juno",
        "slug": "juno",
        "order": 5,
        "category": {"name": "Astrology Asteroid", "slug": "astrology-asteroid"},
    },
    {
        "name": "Vesta",
        "slug": "vesta",
        "order": 6,
        "category": {"name": "Astrology Asteroid", "slug": "astrology-asteroid"},
    },
]

ASTROLOGY_ASPECTS = [
    {
        "name": "Conjunction",
        "slug": "conjunction",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Sextile",
        "slug": "sextile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Square",
        "slug": "square",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Trine",
        "slug": "trine",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Opposition",
        "slug": "opposition",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Quincunx",
        "slug": "quincunx",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Semisextile",
        "slug": "semisextile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Semisquare",
        "slug": "semisquare",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Sesquiquadrate",
        "slug": "sesquiquadrate",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Quintile",
        "slug": "quintile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Biquintile",
        "slug": "biquintile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Novile",
        "slug": "novile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Binovile",
        "slug": "binovile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Tredecile",
        "slug": "tredecile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Septile",
        "slug": "septile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Biseptile",
        "slug": "biseptile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
    {
        "name": "Tredecile",
        "slug": "tredicile",
        "category": {"name": "Astrology Aspect", "slug": "astrology-aspect"},
    },
]

ASTROLOGY_HOUSES = [
    {
        "name": "First House (Ascendant)",
        "slug": "first-house",
        "order": 1,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Second House",
        "slug": "second-house",
        "order": 2,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Third House",
        "slug": "third-house",
        "order": 3,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Fourth House (Imum Coeli)",
        "slug": "fourth-house",
        "order": 4,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Fifth House",
        "slug": "fifth-house",
        "order": 5,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Sixth House",
        "slug": "sixth-house",
        "order": 6,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Seventh House (Descendant)",
        "slug": "seventh-house",
        "order": 7,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Eighth House",
        "slug": "eighth-house",
        "order": 8,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Ninth House",
        "slug": "ninth-house",
        "order": 9,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Tenth House (Medium Coeli)",
        "slug": "tenth-house",
        "order": 10,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Eleventh House",
        "slug": "eleventh-house",
        "order": 11,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
    {
        "name": "Twelfth House",
        "slug": "twelfth-house",
        "order": 12,
        "category": {"name": "Astrology House", "slug": "astrology-house"},
    },
]

MODALITIES = [
    {
        "name": "Cardinal",
        "slug": "cardinal",
        "category": {"name": "Modality", "slug": "modality"},
    },
    {
        "name": "Fixed",
        "slug": "fixed",
        "category": {"name": "Modality", "slug": "modality"},
    },
    {
        "name": "Mutable",
        "slug": "mutable",
        "category": {"name": "Modality", "slug": "modality"},
    },
]

POLARITIES = [
    {"name": "Positive", "slug": "positive", "category": {"name": "Polarity", "slug": "polarity"}},
    {"name": "Negative", "slug": "negative", "category": {"name": "Polarity", "slug": "polarity"}},
]


CHAKRAS = [
    {
        "name": "Root Chakra (Muladhara)",
        "slug": "root",
        "category": {"name": "Chakra", "slug": "chakra"},
    },
    {
        "name": "Sacral Chakra (Svadhisthana)",
        "slug": "sacral",
        "category": {"name": "Chakra", "slug": "chakra"},
    },
    {
        "name": "Solar Plexus Chakra (Manipura)",
        "slug": "solar-plexus",
        "category": {"name": "Chakra", "slug": "chakra"},
    },
    {
        "name": "Heart Chakra (Anahata)",
        "slug": "heart",
        "category": {"name": "Chakra", "slug": "chakra"},
    },
    {
        "name": "Throat Chakra (Vishuddha)",
        "slug": "throat",
        "category": {"name": "Chakra", "slug": "chakra"},
    },
    {
        "name": "Third Eye Chakra (Ajna)",
        "slug": "third-eye",
        "category": {"name": "Chakra", "slug": "chakra"},
    },
    {
        "name": "Crown Chakra (Sahasrara)",
        "slug": "crown",
        "category": {"name": "Chakra", "slug": "chakra"},
    },
]

RUNES = [
    {"name": "Fehu (Wealth)", "slug": "fehu", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Uruz (Strength)", "slug": "uruz", "category": {"name": "Rune", "slug": "rune"}},
    {
        "name": "Thurisaz (Protection)",
        "slug": "thurisaz",
        "category": {"name": "Rune", "slug": "rune"},
    },
    {"name": "Ansuz (Wisdom)", "slug": "ansuz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Raidho (Journey)", "slug": "raidho", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Kenaz (Knowledge)", "slug": "kenaz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Gebo (Partnership)", "slug": "gebo", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Wunjo (Joy)", "slug": "wunjo", "category": {"name": "Rune", "slug": "rune"}},
    {
        "name": "Hagalaz (Transformation)",
        "slug": "hagalaz",
        "category": {"name": "Rune", "slug": "rune"},
    },
    {"name": "Nauthiz (Need)", "slug": "nauthiz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Isa (Stillness)", "slug": "isa", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Jera (Harvest)", "slug": "jera", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Eihwaz (Connection)", "slug": "eihwaz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Perth (Mystery)", "slug": "perth", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Algiz (Protection)", "slug": "algiz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Sowilo (Success)", "slug": "sowilo", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Tiwaz (Victory)", "slug": "tiwaz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Berkano (Growth)", "slug": "berkano", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Ehwaz (Movement)", "slug": "ehwaz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Mannaz (Humanity)", "slug": "mannaz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Laguz (Flow)", "slug": "laguz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Ingwaz (Potential)", "slug": "ingwaz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Dagaz (Breakthrough)", "slug": "dagaz", "category": {"name": "Rune", "slug": "rune"}},
    {"name": "Othala (Heritage)", "slug": "othala", "category": {"name": "Rune", "slug": "rune"}},
]

SEPHIROTH = [
    {
        "name": "Kether (Crown)",
        "slug": "kether",
        "order": 1,
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
    {
        "name": "Chokmah (Wisdom)",
        "slug": "chokmah",
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
    {
        "name": "Binah (Understanding)",
        "slug": "binah",
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
    {
        "name": "Chesed (Mercy)",
        "slug": "chesed",
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
    {
        "name": "Geburah (Strength)",
        "slug": "geburah",
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
    {
        "name": "Tiphareth (Beauty)",
        "slug": "tiphareth",
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
    {
        "name": "Netzach (Victory)",
        "slug": "netzach",
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
    {
        "name": "Hod (Splendor)",
        "slug": "hod",
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
    {
        "name": "Yesod (Foundation)",
        "slug": "yesod",
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
    {
        "name": "Malkuth (Kingdom)",
        "slug": "malkuth",
        "category": {"name": "Sephiroth", "slug": "sephiroth"},
    },
]

HEBREW_LETTERS = [
    {
        "name": "Aleph",
        "slug": "aleph",
        "letter": "א",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Beth",
        "slug": "beth",
        "letter": "ב",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Gimel",
        "slug": "gimel",
        "letter": "ג",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Daleth",
        "slug": "daleth",
        "letter": "ד",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "He",
        "slug": "he",
        "letter": "ה",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Vav",
        "slug": "vav",
        "letter": "ו",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Zayin",
        "slug": "zayin",
        "letter": "ז",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Chet",
        "slug": "chet",
        "letter": "ח",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Tet",
        "slug": "tet",
        "letter": "ט",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Yod",
        "slug": "yod",
        "letter": "י",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Kaf",
        "slug": "kaf",
        "letter": "כ",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Lamed",
        "slug": "lamed",
        "letter": "ל",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Mem",
        "slug": "mem",
        "letter": "מ",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Nun",
        "slug": "nun",
        "letter": "נ",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Samekh",
        "slug": "samekh",
        "letter": "ס",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Ayin",
        "slug": "ayin",
        "letter": "ע",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Pe",
        "slug": "pe",
        "letter": "פ",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Tsadi",
        "slug": "tsadi",
        "letter": "צ",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Qof",
        "slug": "qof",
        "letter": "ק",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Resh",
        "slug": "resh",
        "letter": "ר",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Shin",
        "slug": "shin",
        "letter": "ש",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
    {
        "name": "Tav",
        "slug": "tav",
        "letter": "ת",
        "category": {"name": "Hebrew Letter", "slug": "hebrew-letter"},
    },
]

KABBALAH_WORLDS = [
    {
        "name": "Atziluth (Emanation)",
        "slug": "atziluth",
        "category": {"name": "Kabbalah World", "slug": "kabbalah-world"},
    },
    {
        "name": "Briah (Creation)",
        "slug": "briah",
        "category": {"name": "Kabbalah World", "slug": "kabbalah-world"},
    },
    {
        "name": "Yetzirah (Formation)",
        "slug": "yetzirah",
        "category": {"name": "Kabbalah World", "slug": "kabbalah-world"},
    },
    {
        "name": "Assiah (Action)",
        "slug": "assiah",
        "category": {"name": "Kabbalah World", "slug": "kabbalah-world"},
    },
]

SOLFEGGIOS = [
    {"name": "Do", "slug": "do", "category": {"name": "Solfeggio", "slug": "solfeggio"}},
    {"name": "Re", "slug": "re", "category": {"name": "Solfeggio", "slug": "solfeggio"}},
    {"name": "Mi", "slug": "mi", "category": {"name": "Solfeggio", "slug": "solfeggio"}},
    {"name": "Fa", "slug": "fa", "category": {"name": "Solfeggio", "slug": "solfeggio"}},
    {"name": "Sol", "slug": "sol", "category": {"name": "Solfeggio", "slug": "solfeggio"}},
    {"name": "La", "slug": "la", "category": {"name": "Solfeggio", "slug": "solfeggio"}},
    {"name": "Ti", "slug": "ti", "category": {"name": "Solfeggio", "slug": "solfeggio"}},
]

WEEKDAYS = [
    {"name": "Monday", "slug": "monday", "category": {"name": "Weekday", "slug": "weekday"}},
    {"name": "Tuesday", "slug": "tuesday", "category": {"name": "Weekday", "slug": "weekday"}},
    {"name": "Wednesday", "slug": "wednesday", "category": {"name": "Weekday", "slug": "weekday"}},
    {"name": "Thursday", "slug": "thursday", "category": {"name": "Weekday", "slug": "weekday"}},
    {"name": "Friday", "slug": "friday", "category": {"name": "Weekday", "slug": "weekday"}},
    {"name": "Saturday", "slug": "saturday", "category": {"name": "Weekday", "slug": "weekday"}},
    {"name": "Sunday", "slug": "sunday", "category": {"name": "Weekday", "slug": "weekday"}},
]

ELEMENTS = [
    {"name": "Earth", "slug": "earth", "category": {"name": "Element", "slug": "element"}},
    {"name": "Air", "slug": "air", "category": {"name": "Element", "slug": "element"}},
    {"name": "Fire", "slug": "fire", "category": {"name": "Element", "slug": "element"}},
    {"name": "Water", "slug": "water", "category": {"name": "Element", "slug": "element"}},
]

COLORS = [
    {"name": "Black", "slug": "black", "category": {"name": "Color", "slug": "color"}},
    {"name": "White", "slug": "white", "category": {"name": "Color", "slug": "color"}},
    {"name": "Red", "slug": "red", "category": {"name": "Color", "slug": "color"}},
    {"name": "Orange", "slug": "orange", "category": {"name": "Color", "slug": "color"}},
    {"name": "Yellow", "slug": "yellow", "category": {"name": "Color", "slug": "color"}},
    {"name": "Green", "slug": "green", "category": {"name": "Color", "slug": "color"}},
    {"name": "Blue", "slug": "blue", "category": {"name": "Color", "slug": "color"}},
    {"name": "Indigo", "slug": "indigo", "category": {"name": "Color", "slug": "color"}},
    {"name": "Violet", "slug": "violet", "category": {"name": "Color", "slug": "color"}},
    {"name": "Pink", "slug": "pink", "category": {"name": "Color", "slug": "color"}},
    {"name": "Brown", "slug": "brown", "category": {"name": "Color", "slug": "color"}},
    {"name": "Gray", "slug": "gray", "category": {"name": "Color", "slug": "color"}},
]

GEMSTONES = [
    {"name": "Garnet", "slug": "garnet", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {"name": "Amethyst", "slug": "amethyst", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {
        "name": "Aquamarine",
        "slug": "aquamarine",
        "category": {"name": "Gemstone", "slug": "gemstone"},
    },
    {"name": "Diamond", "slug": "diamond", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {"name": "Emerald", "slug": "emerald", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {"name": "Pearl", "slug": "pearl", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {"name": "Ruby", "slug": "ruby", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {"name": "Peridot", "slug": "peridot", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {"name": "Sapphire", "slug": "sapphire", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {"name": "Opal", "slug": "opal", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {"name": "Topaz", "slug": "topaz", "category": {"name": "Gemstone", "slug": "gemstone"}},
    {
        "name": "Turquoise",
        "slug": "turquoise",
        "category": {"name": "Gemstone", "slug": "gemstone"},
    },
]

METALS = [
    {"name": "Gold", "slug": "gold", "category": {"name": "Metal", "slug": "metal"}},
    {"name": "Mercury", "slug": "mercury", "category": {"name": "Metal", "slug": "metal"}},
    {"name": "Copper", "slug": "copper", "category": {"name": "Metal", "slug": "metal"}},
    {"name": "Silver", "slug": "silver", "category": {"name": "Metal", "slug": "metal"}},
    {"name": "Iron", "slug": "iron", "category": {"name": "Metal", "slug": "metal"}},
    {"name": "Tin", "slug": "tin", "category": {"name": "Metal", "slug": "metal"}},
    {"name": "Lead", "slug": "lead", "category": {"name": "Metal", "slug": "metal"}},
]

NUMBERS = [
    {"name": "One", "slug": "one", "category": {"name": "Number", "slug": "number"}},
    {"name": "Two", "slug": "two", "category": {"name": "Number", "slug": "number"}},
    {"name": "Three", "slug": "three", "category": {"name": "Number", "slug": "number"}},
    {"name": "Four", "slug": "four", "category": {"name": "Number", "slug": "number"}},
    {"name": "Five", "slug": "five", "category": {"name": "Number", "slug": "number"}},
    {"name": "Six", "slug": "six", "category": {"name": "Number", "slug": "number"}},
    {"name": "Seven", "slug": "seven", "category": {"name": "Number", "slug": "number"}},
    {"name": "Eight", "slug": "eight", "category": {"name": "Number", "slug": "number"}},
    {"name": "Nine", "slug": "nine", "category": {"name": "Number", "slug": "number"}},
    {"name": "Ten", "slug": "ten", "category": {"name": "Number", "slug": "number"}},
    {"name": "Eleven", "slug": "eleven", "category": {"name": "Number", "slug": "number"}},
    {"name": "Twelve", "slug": "twelve", "category": {"name": "Number", "slug": "number"}},
    {"name": "Thirteen", "slug": "thirteen", "category": {"name": "Number", "slug": "number"}},
    {"name": "Fourteen", "slug": "fourteen", "category": {"name": "Number", "slug": "number"}},
    {"name": "Fifteen", "slug": "fifteen", "category": {"name": "Number", "slug": "number"}},
    {"name": "Sixteen", "slug": "sixteen", "category": {"name": "Number", "slug": "number"}},
    {"name": "Seventeen", "slug": "seventeen", "category": {"name": "Number", "slug": "number"}},
    {"name": "Eighteen", "slug": "eighteen", "category": {"name": "Number", "slug": "number"}},
    {"name": "Nineteen", "slug": "nineteen", "category": {"name": "Number", "slug": "number"}},
    {"name": "Twenty", "slug": "twenty", "category": {"name": "Number", "slug": "number"}},
    {"name": "Twenty One", "slug": "twenty-one", "category": {"name": "Number", "slug": "number"}},
    {"name": "Twenty Two", "slug": "twenty-two", "category": {"name": "Number", "slug": "number"}},
    {
        "name": "Twenty Three",
        "slug": "twenty-three",
        "category": {"name": "Number", "slug": "number"},
    },
    {
        "name": "Twenty Four",
        "slug": "twenty-four",
        "category": {"name": "Number", "slug": "number"},
    },
    {
        "name": "Twenty Five",
        "slug": "twenty-five",
        "category": {"name": "Number", "slug": "number"},
    },
    {"name": "Twenty Six", "slug": "twenty-six", "category": {"name": "Number", "slug": "number"}},
    {
        "name": "Twenty Seven",
        "slug": "twenty-seven",
        "category": {"name": "Number", "slug": "number"},
    },
    {
        "name": "Twenty Eight",
        "slug": "twenty-eight",
        "category": {"name": "Number", "slug": "number"},
    },
    {
        "name": "Twenty Nine",
        "slug": "twenty-nine",
        "category": {"name": "Number", "slug": "number"},
    },
    {"name": "Thirty", "slug": "thirty", "category": {"name": "Number", "slug": "number"}},
    {"name": "Thirty One", "slug": "thirty-one", "category": {"name": "Number", "slug": "number"}},
    {"name": "Thirty Two", "slug": "thirty-two", "category": {"name": "Number", "slug": "number"}},
]
