/**
 * Shared conventional commit configuration
 *
 * This file is the single source of truth for types, scopes, and emoji mappings used across:
 * - commitlint.config.ts (commit message validation)
 * - validate-branch-name.config.js (branch name validation)
 * - release.config.cjs (release rules and changelog sections)
 * - .vscode/settings.json (scope autocomplete)
 * - documentation/skills/commit-code/SKILL.md (reference tables)
 *
 * When adding/removing types, scopes, or emojis, update this file only.
 * Run `nx run monorepo:sync-conventional-config:write` to propagate changes.
 */

/**
 * Canonical gitmoji — one emoji per commit type.
 * Each entry is the source of truth for the type key, its description, and its canonical emoji.
 * See documentation/gitmoji.md for the full list of available emojis.
 */
const types = [
  {
    emoji: "✨",
    code: ":sparkles:",
    name: "feat",
    description: "A new feature or capability that adds value for users",
  },
  {
    emoji: "🐛",
    code: ":bug:",
    name: "fix",
    description: "A bug fix that addresses a specific issue or problem",
  },
  {
    emoji: "📝",
    code: ":memo:",
    name: "docs",
    description:
      "Documentation, AGENTS.md, SKILL.md, README, and planning files",
  },
  {
    emoji: "🧪",
    code: ":test_tube:",
    name: "test",
    description: "Adding or correcting unit, integration, or end-to-end tests",
  },
  {
    emoji: "♻️",
    code: ":recycle:",
    name: "refactor",
    description:
      "Code restructuring that neither fixes a bug nor adds a feature",
  },
  {
    emoji: "🎨",
    code: ":art:",
    name: "style",
    description:
      "Formatting, whitespace, or code structure changes with no semantic effect",
  },
  {
    emoji: "⚡️",
    code: ":zap:",
    name: "perf",
    description:
      "A code change that improves performance (caching, query optimization, etc.)",
  },
  {
    emoji: "🔧",
    code: ":wrench:",
    name: "chore",
    description:
      "Housekeeping that doesn't modify src or test files (gitignore, editor config, etc.)",
  },
  {
    emoji: "👷",
    code: ":construction_worker:",
    name: "ci",
    description:
      "GitHub Actions workflows, composite actions, and CI/CD scripts",
  },
  {
    emoji: "📦️",
    code: ":package:",
    name: "build",
    description:
      "Build system, Vite/Docker/Helm config, or external dependency integration",
  },
  {
    emoji: "⏪️",
    code: ":rewind:",
    name: "revert",
    description: "Reverts a previous commit",
  },
];

const scopes = [
  {
    name: "affirmations",
    description:
      "Python Jupyter notebook application for LangGraph affirmation generation",
  },
  {
    name: "applications",
    description:
      "Changes spanning multiple applications in applications/ (e.g. lexico, caelundas, etc.)",
  },
  {
    name: "caelundas",
    description:
      "Node.js CLI for astronomical calendar generation (NASA JPL ephemeris)",
  },
  {
    name: "configuration",
    description:
      "Workspace root config files (tsconfig, eslint, vitest, nx.json, etc.)",
  },
  {
    name: "conformance",
    description:
      "Code generator templates and conformance validation tests for generated instances",
  },
  {
    name: "dependencies",
    description:
      "Dependency version changes (upgrades, additions, removals via pnpm)",
  },
  {
    name: "deployments",
    description: "GitHub Actions workflows and CI/CD pipeline configuration",
  },
  {
    name: "documentation",
    description: "Markdown docs, skills, planning files, and AGENTS.md files",
  },
  {
    name: "infrastructure",
    description: "Helm charts, Terraform configs, and Kubernetes resources",
  },
  {
    name: "JimmyPaolini",
    description: "Static GitHub profile README project (markdown and assets)",
  },
  {
    name: "lexico",
    description:
      "TanStack Start SSR Latin dictionary web app with Supabase backend",
  },
  {
    name: "lexico-components",
    description: "Shared React/shadcn component library",
  },
  {
    name: "lexico-entities",
    description: "Shared TypeORM entities and GraphQL types",
  },
  {
    name: "lexico-ingestion",
    description: "Data ingestion scripts for Lexico",
  },
  {
    name: "monorepo",
    description:
      "Workspace root concerns (pnpm-workspace, root package.json, Nx orchestration)",
  },
  {
    name: "no-release",
    description: "Escape hatch: suppress semantic-release for any commit type",
  },
  {
    name: "packages",
    description: "Changes spanning multiple shared packages in packages/",
  },
  {
    name: "release",
    description:
      "Version bumps and release commits generated by semantic-release",
  },
  {
    name: "scripts",
    description:
      "Shell and TypeScript scripts in scripts/ (sync, setup, utilities)",
  },
  {
    name: "testing",
    description:
      "Vitest configuration, shared test utilities, and coverage setup",
  },
  {
    name: "tools",
    description: "Changes spanning multiple tool projects in tools/",
  },
];

module.exports = { types, scopes };
