import { defineConfig } from "oxfmt";

export default defineConfig({
  arrowParens: "always",
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: "auto",
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "css",
  ignorePatterns: [
    "!**/*.d.ts.map",
    "**/*.d.ts",
    "**/.venv",
    "**/*.md",
    "**/*.mdx",
    "**/.next",
    "**/.nx",
    "**/.terraform/**",
    "**/build",
    "**/coverage",
    "**/dist",
    "**/helm/**/templates/**",
    "**/node_modules",
    "**/out",
    "**/routeTree.gen.ts",
    "**/tmp",
    "*.log",
    "*.min.css",
    "*.min.js",
    "*.tmp",
    ".git",
    ".idea",
    ".next",
    ".nx",
    ".nyc_output",
    ".vscode",
    "build",
    "CHANGELOG.md",
    "coverage",
    "dist",
    "**/infrastructure/helm/**/templates/**",
    "node_modules",
    "out",
    "package-lock.json",
    "**/packages/lexico-components/src/components/**",
    "**/packages/lexico-components/src/hooks/**",
    "**/packages/lexico-components/src/lib/**",
    "**/applications/lexico-ingestion/data/**",
    "**/applications/lexico-ingestion/data/library/**",
    "**/applications/lexico-ingestion/src/modules/literature/literature.constants.ts",
    "**/applications/lexico-ingestion/src/modules/library/library.constants.ts",
    "**/library.json",
    "pnpm-lock.yaml",
    "tmp",
    "**/conformance/**/templates/**",
    "**/data/wikipedia",
    "**/data/wiktionary",
    "yarn.lock",
  ],
  insertPragma: false,
  jsxSingleQuote: false,
  printWidth: 80,
  proseWrap: "preserve",
  quoteProps: "as-needed",
  rangeEnd: null,
  rangeStart: 0,
  requirePragma: false,
  semi: true,
  singleAttributePerLine: true,
  singleQuote: false,
  sortPackageJson: false,
  tabWidth: 2,
  trailingComma: "all",
  useTabs: false,
  vueIndentScriptAndStyle: false,
});
