name: 🦸 Release Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-version:
    name: 🦸 Release Version
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 🕋 Setup Monorepo
        uses: ./.github/actions/setup-monorepo

      - name: 🔐 Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: 🔎 Check Commit Signing Configuration
        run: bash scripts/git/check-commit-signing-configuration.sh

      - name: 🦸 Release Version
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: pnpm semantic-release
